#ifndef _USER_DEFINE_H_
#define _USER_DEFINE_H_

#define MOTOR0_DIR0_PORT	GPIOB
#define MOTOR0_DIR1_PORT	GPIOB
#define MOTOR0_DIR0_PIN		GPIO_PIN_4
#define MOTOR0_DIR1_PIN		GPIO_PIN_5
#define MOTOR0_TIMER		htim4
#define MOTOR0_CHANNEL		TIM_CHANNEL_3

#define MOTOR1_DIR0_PORT	GPIOA
#define MOTOR1_DIR1_PORT	GPIOB
#define MOTOR1_DIR0_PIN		GPIO_PIN_15
#define MOTOR1_DIR1_PIN		GPIO_PIN_3
#define MOTOR1_TIMER		htim4
#define MOTOR1_CHANNEL		TIM_CHANNEL_4

//#define MOTOR0_REVERT
//#define MOTOR1_REVERT

#endif
